### PR TITLE
Upgrade deps, setup linter (CI)

### PR DESCRIPTION
**Pull request by vladimyr**
- adding `lint` script
- setup travis ci
- adding `.editorconfig`

### CODE REVIEW

**Comment by vladimyr** [comment]
You can see Travis logs here: https://travis-ci.com/vladimyr/rollup-plugin-visualizer

**Comment by btd** [comment]
Thank you for PR.
For me it is very unclear what you tried to do with tests.
Please remove 'test' dir and test package.json command from package.json and travis. It is makes much more sense to add build step to travis instead, it is the best test.

**Comment by vladimyr** [comment]
I didn't add, it was there already. I've just put test script inside package.json as preparation step towards fully working test suite. But if you want I'll remove it altogether?

**Comment by btd** [comment]
Sorry, yes. I now remember was a bug and i added text fixture to be able to reproduce it.
Ok, looks good to me

**Comment by vladimyr** [comment]
> It is makes much more sense to add build step to travis instead, it is the best test.

Indeed, I did that here: #33

**Pull request merged**
