### PR TITLE
Add bundle name to leaves

### PR DESCRIPTION
**Pull request by benatshippabo**
## Feature

Adds bundle id to every node for easier referencing when generating the `stats.json`.

image

### CODE REVIEW

**Comment by btd** [comment]
Hi, can you please explain your usecase?

**Comment by benatshippabo** [comment]
> Hi, can you please explain your usecase?

Hi @btd. My team wants to track file addition and deletion to bundles more easily. We are thinking of committing the `stats.json` file to git after filtering with `jq .tree stats.json | sed -i '/uid/d'`. The idea is for the git diff to show us which file was added or removed from each bundle.

**Comment by btd** [comment]
Are you interested what files specifically in specific bundle or in files in general?
If second i think you would better to try something like: `jq -r '.nodeMetas | keys[] as $k | .[$k].id'`

**Comment by benatshippabo** [comment]
> 

The first option. Optimally, we want something that looks like this:

image

In the example, someone added redux as a dependency and using the git diff it is more clear why the bundle size went up.

**Comment by benatshippabo** [comment]
Found a way to do it with `jq`

```sh
jq '[ .tree.children[] | .name as $bundle | recurse(.children[]?)? | { file: .name, bundle: $bundle } ]' stats.json
```

**Pull request closed without merging**
